import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import Splash from './components/Splash';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EcoSnap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
				<meta name='viewport' content='initial-scale=1, viewport-fit=cover, minimal-ui'/>
      </Head>

      <main className={styles.main}>
        <Splash />
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
